services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./seed-data:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: unless-stopped

  # Backend
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "9001:9001"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=9001
      - DATABASE_URL=mongodb://mongodb:27017/lynk
      - JWT_KEY=chiavesefgrettt99
      - ORIGIN=http://localhost
      - CLIENT_URL=http://localhost
      - MAILTRAP_ENDPOINT=https://send.api.mailtrap.io/
      - MAILTRAP_TOKEN=2a0685e165c1a4e00257fa44bb07d0b5
    volumes:
      - ./server:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    networks:
      - app-network
    restart: unless-stopped

  # Frontend
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        # Pass whichever URL you want
        VITE_SERVER_URL: "http://localhost:9001"
    container_name: client
    ports:
      - "80:80"
    depends_on:
      - server
    # You can remove environment: - VITE_SERVER_URL=...
    # because it's overshadowed by the build args
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  uploads_data:
